spring.data.mongodb.uri=mongodb+srv://mohdkaif8672:kaif786@cluster0.opfmb.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=myjournaldb
spring.data.mongodb.auto-index-creation=true
spring.redis.host=localhost
spring.redis.port=6379
api.key=4678f9c399012d68ce59292f70236982
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mohdkaif8672@gmail.com
spring.mail.password=eitv jqzu cibs hepd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
server.port=8081